package com.ovfintech.bynz.service;


import com.github.pagehelper.PageInfo;

import java.util.List;
import java.util.Map;

/**
 * Service CommonOperate
 * This code is generated by the Hen, strongly recommended not to modify directly.
 */
public interface SysDictService {
    
    List<Map<String, Object>> getInitSysDictList();
    
    PageInfo<List<Map<String, Object>>> getSysDictList();
}

