# =======================================
# ===============注册中心配置==============
# =======================================
# 注册中心配置

#客户端配置
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://XXXXX/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#日志级别配置，不同环境不一致
logging:
  level:
    com:
      xyz:
        caofancpu:
          trackingtime:
            #DTO数据库操作日志级别
            mapper: debug
    org:
      springframework:
        #Spring框架日志级别
        web: error
        boot:
          autoconfigure: error
#模拟服务所在网关路由/nginx配置
server:
  servlet:
    context-path: /trackingTime
#数据库配置
spring:
  datasource:
    connection-test-query: select 1
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_clould?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(ISF7rTrUFxKY7SN/PNvvWg==)
jasypt:
  encryptor:
    password: e!JdljyJ^e4I5oU
  http:
    #文件上传大小限制
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  #Kafka配置
  kafka:
    #Kafka消息中心访问URL
    bootstrap-servers: 192.168.2.70:9092
    #Kafka客户端组名配置
    consumer:
      group-id: caofanGroup

task:
  handle:
    average:  10
  rootPath: /work/xx
  resultPath: /work/ff

local:
  oss:
    upload: /work/OSS/UP
    download: /work/OSS/DL

wx:
  domain: https://caofancpu.github.io
# 部署运行命令
#    nohup java -server -Xmx512M -Xms512M -multipliers:NewRatio=2 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=58084 -jar XXX.jar &
