package com.xyz.caofancpu.service;


import com.xyz.caofancpu.model.Attachment;
import com.xyz.caofancpu.result.GlobalErrorInfoException;
import org.springframework.web.multipart.MultipartFile;

/**
 * Service CommonOperate
 * This code is generated by the Hen, strongly recommended not to modify directly.
 */
public interface CommonOperateService {
    
    /**
     * 上传附件
     *
     * @param attachment
     * @param file
     * @throws GlobalErrorInfoException
     */
    void uploadAttachment(Attachment attachment, MultipartFile file)
            throws GlobalErrorInfoException;
    
    /**
     * 获取附件
     *
     * @param attachmentName
     * @return
     * @throws GlobalErrorInfoException
     */
    String getAttachmentAccessUrl(String attachmentName)
            throws GlobalErrorInfoException;
    
    String loadToken();
}

