package com.xyz.caofancpu.trackingtime.service.impl;


import com.github.pagehelper.PageHelper;
import com.github.pagehelper.PageInfo;
import com.xyz.caofancpu.trackingtime.mapper.SysDictMapper;
import com.xyz.caofancpu.trackingtime.service.SysDictService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.DependsOn;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;


/**
 * ServiceImpl CommonOperate
 * This code is generated by the Hen, strongly recommended not to modify directly.
 */
@Service("sysDictService")
@DependsOn("initContextPropertyInitializer")
@Slf4j
public class SysDictServiceImpl implements SysDictService {
    @SuppressWarnings("SpringJavaInjectionPointsAutowiringInspection")
    @Autowired
    private transient SysDictMapper sysDictMapper;

    @Override
    public List<Map<String, Object>> getInitSysDictList() {
        return sysDictMapper.getInitSysDictList();
    }

    @Override
    public PageInfo<List<Map<String, Object>>> getSysDictList() {
        PageHelper.startPage(1, 10);
        List<Map<String, Object>> resultList = sysDictMapper.getSysDictList();
        return (PageInfo<List<Map<String, Object>>>) new PageInfo(resultList);
    }
}

