-- auto Generated on 2019-08-14 17:22:39 
-- DROP TABLE IF EXISTS `time_block`; 
CREATE TABLE time_block(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `user_id` BIGINT NOT NULL DEFAULT -1 COMMENT '用户ID',
    `start_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '起始时间',
    `end_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '结束时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'time_block';


