package com.xyz.caofancpu.service;


import com.github.pagehelper.PageInfo;
import com.xyz.caofancpu.model.SysConfigDictMo;

import java.util.List;

/**
 * Service CommonOperate
 * This code is generated by the Hen, strongly recommended not to modify directly.
 */
public interface SysDictService {

    List<SysConfigDictMo> getInitSysDictList();

    PageInfo<List<SysConfigDictMo>> getSysDictList();

    void batchAddConfig(List<SysConfigDictMo> sysConfigDictMoList);
}

