#应用配置
app:
  name: www.caofanCPU.com

application:
  version: 1.0.0

#注册中心配置
eureka:
  client:
    registryFetchIntervalSeconds: 5
  instance:
    leaseExpirationDurationInSeconds: 10
    leaseRenewalIntervalInSeconds: 5
#文件访问系统配置
ms:
  file:
    url: http://SERVICE-FILE
  sso:
    url: http://SERVICE-SSO
#日志系统配置
logging:
  config: classpath:logback-spring.xml
#Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  type-aliases-package: com.xyz..*.model
# mapper.xml文件置于Resource中的mybatis文件映射配置
# mapper-locations: classpath*:mybatis/**/*.xml

#pagehelper的配置
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  reasonable: true
  autoRuntimeDialect: true
  params: count=countSql
  supportMethodsArguments: true


#资源路径键名配置
resource_access_key: DEBUGGER_RESOURCE
#网关内部队列配置
ribbon:
  ServerListRefreshInterval: 2000
#服务部署端口
server:
  port: 8098
#排除部分装配, 加速启动
management:
  add-application-context-header: false
#Spring配置
spring:
  #服务部署名
  application:
    name: service-debuggerking
  mvc:
    formcontent:
      filter:
        enabled: false
  # 可选禁用的
  # org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration,\
  # org.springframework.boot.autoconfigure.websocket.WebSocketMessagingAutoConfiguration,\
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration,\
      org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,\
      org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration,\
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
      org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration,\
      org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration,\
      org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration,\
      org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration,\
      org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration,\
      org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration,\
      org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration,\
      org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration,\
      org.springframework.boot.actuate.autoconfigure.TraceRepositoryAutoConfiguration,\
      org.springframework.boot.actuate.autoconfigure.TraceWebFilterAutoConfiguration,\
      org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    #当前环境
    active: dev
#自定义卡夫卡主题
test:
  spring:
    kafka:
      topics: caofanCPU,demo
#用户中心服务配置
user-profile-url: http://USER-SERVICE

# swagger认证配置
swagger:
  authPathRegex: ^(?!auth).*$
  showApi: true
  authorizationKey: Authorization

# 系统间认证KEY
authorization:
  user-profile:
    key: Authorization

fileOperate:
  # 针对文件操作接口, 是否打印文件内容参数
  # 不建议日志中打印文件内容, 因此此key对应的值默认为false
  logging:
    key: openFileOperateLogging
    value: false


# 部署运行命令
#    nohup java -server -Xmx512M -Xms512M -multipliers:NewRatio=2 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=58084 -jar XXX.jar &
